version: '3'
services: 
    app:
        build: ./docker/python
        environment:
            - TZ=Asia/Tokyo
        volumes:
            - ./:/home/python/app
        expose:
            - "8081"
    db:
        build: ./docker/mysql
        volumes:
            - db-store:/var/lib/mysql
        ports:
            - ${MYSQL_PORT}:3306
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - TZ=${TZ}
    nginx:
        image: nginx:1.16
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/nginx/uwsgi_params:/etc/nginx/uwsgi_params
            # - ./static:/static
        depends_on:
            - app
volumes:
    db-store:
    